App.js, components/Comment.jsx, components/Post.jsx, views/Comments.jsx, views/Feed.jsx
Looks bunk and can't write anything, but hey
<br />
<br />
=> Adds basic comments feed

components/CreateResourceModal.jsx, views/Comments.jsx, views/Feed.jsx
We can write posts and comments!
=> Adds creating resource functionality

components/ChannelList.jsx, components/ProfileHeader.jsx, styles/styles.js, views/Home.jsx
Adds clickable bells to sub/unsub from channels. Viewing my subscriptions still does nothing :)
=> Enable subscription functionality & pretty up home

views/Feed.jsx, views/Home.jsx
Use the new api route to get the posts from your subbed channels
=> Make my subscriptions channel actually get just your subscriptions

components/CreateResourceModal.jsx, components/ProfileHeader.jsx
Makes the modals a lot nicer and adds ability to get rid of it by tapping away
=> Better Modals

components/ChannelList.jsx, components/Comment.jsx, components/ContentBar.jsx, components/Post.jsx, styles/styles.js, views/Comments.jsx, views/Feed.jsx
Make the app prettier (Although who am I to judge?)
=> Enhance the UI

app.json, components/Post.jsx, views/Comments.jsx, views/Feed.jsx
- Still show the post if there's no comments
- If a post is show long, cut it off in the feed view - see the full post by clicking on it
- Build config
=> Some qol changes

App.js, components/ChannelList.jsx, components/ProfileHeader.jsx, config.js, rn-cli.config.js, styles/styles.js, views/Comments.jsx, views/Feed.jsx, views/Home.jsx, views/Login.jsx, views/Settings.jsx, views/Splash.jsx
Adds app version under help,
Adds logout button under settings,
adds autologin if you're already logged in
=> App version, auto-login, and logout button

components/Post.jsx, styles/styles.js
makes the feed a little more appealing
=> Sleeker cards

ApiClient.js, components/Comment/Comment.jsx, components/Comment/CommentStyle.js, components/Post/Post.jsx, components/Post/PostStyle.js, views/Comments/Comments.jsx, views/Feed/Feed.jsx
It's ugly and full of bugs, but aren't we all
=> Deleting and editing for posts AND comments!

components/CreateResourceModal/CreateResourceModal.jsx, components/CreateResourceModal/CreateResourceModalStyle.js, components/Post/Post.jsx, components/ProfileHeader/ProfileHeader.jsx, package-lock.json, package.json, yarn.lock
Should fix profile pic and keyboard avoiding post/comment textbox. Hopefully implements swiping down to dismiss keyboard on iOS as well as android, couldn't test it on a real iphone but emulator results seemed promising. Login view is a bit better but still probably bunk on small devices.
=> Ios bugfixes

components/ChannelList/ChannelList.jsx
Moves subscribed channels to the top, and sorts them by alphabetical order
=> Sort channels

components/Comment/Comment.jsx, components/CreateResourceModal/CreateResourceModal.jsx, components/Post/Post.jsx, package-lock.json, package.json
Adds abillity to post links and clears comment text input on cancel/save
=> Add links & clear comment input

views/Feed/Feed.jsx
=> Fix scroll -> refresh bug

components/Banner/Banner.jsx
Cleans up the messages in the login screen
=> Prettier error/success banners in login

components/ChannelList/ChannelList.jsx, views/Feed/Feed.jsx, views/Home/Home.jsx, yarn.lock
=> Adds My Posts

ApiClient.js, components/ContentBar/ContentBar.jsx, components/CreateResourceModal/CreateResourceModal.jsx, components/CreateResourceModal/CreateResourceModalStyle.js, components/CreateResourceModal/Toolbar/Toolbar.jsx, components/CreateResourceModal/Toolbar/ToolbarStyle.js, components/Post/Post.jsx, components/Post/PostStyle.js, package-lock.json, package.json, views/Comments/Comments.jsx, views/Feed/Feed.jsx
Adds an optional `Toolbar` to the `createResourceModal` via the prop `showToolbar`. This toolbar is enabled on the modal in all feeds. It adds the option to take a picture or select from gallery. Upon choosing an image, a thumbnail is shown in the toolbar of the image. Clicking post will then create the post and upload the image to the post. Posts have also been modified to show images if they exist on a post.
https://www.npmjs.com/package/react-native-scalable-image is used to appropriately scale the images.
closes #30
=> Add ability to add pictures to posts via camera or gallery

components/NotificationList/NotificationList.jsx, components/NotificationList/NotificationListStyle.js, views/Home/Home.jsx, views/Home/HomeTabBar/HomeTabBar.jsx, views/Home/HomeTabBar/HomeTabBarButton/HomeTabBarButton.jsx, views/Home/HomeTabBar/HomeTabBarButton/HomeTabBarButtonStyle.js, views/Login/Login.jsx, views/Splash/Splash.jsx
Adds a notification list component
Adds a tab bar component to home screen
Can toggle between notifications and channels on home screen
Also removes loading user/token from the home screen and instead just passes them as params from the splash screen so we only load them once instead of twice
connect #94
=> Add notifications tab on home screen

helpers/notificationToken.js, views/Comments/Comments.jsx, views/Home/Home.jsx, views/Login/Login.jsx
When viewing a post you couldn't like it or edit comment, this fixes that. Also fixes an issue on login from my last PR. 
Cleans up notification token method a bit for better erros
=> Fixes updating post when viewing it directly and some other cleanup

package-lock.json, views/Home/Home.jsx, views/Home/HomeStyle.js
Adds a button in the notifications tray to mark all as seen
=> Add button to mark all notifications as seen

views/Login/Login.jsx
Just hide the option to register on iOS for app store approval reasons
=> Don't allow registering on iOS

components/Post/Post.jsx, components/Post/PostStyle.js
This doesn't actually do anything yet. Still need to implement flagging server side
=> Add button to flag posts as innappropriate

components/Comment/Comment.jsx, components/Comment/CommentStyle.js, components/Post/Post.jsx, views/Comments/Comments.jsx, views/Feed/Feed.jsx, views/Home/Home.jsx
Admin status set directly on user object (no endpt for this, use script on manually do it). Admins can delete any post or comment, not just their own.
=> Admin priviledges

app.json, components/Post/Post.jsx, config.js
Functionality not implemented but ideally would email webmaster to notify
=> Added the ability to "block" a user (aka just report them)

app.json, components/Post/Post.jsx, components/Post/PostStyle.js, config.js, package-lock.json, package.json, views/Comments/Comments.jsx, views/Feed/Feed.jsx, views/Home/Home.jsx
See who's liked your post!
#99
=> Like visibility

app.json, config.js, views/Home/Home.jsx
Charlotte wants the eye gone
Also version 2.1!
=> Design fixes

app.json, config.js
Bumping the version to 5.0 to solve the April Fools Bug
=> Version bump

views/Comments/Comments.jsx, views/Feed/Feed.jsx
Changed to /posts/:pid/like to be able to prevent users from editing other user's posts
=> Changed to dedicated liking endpoint

components/NoData/NoData.jsx
=> First post image bug

views/Home/Home.jsx
When a user clicks on a notification, it will navigate them to the correct post
#153
=> Notification navigation

components/UserProfile/UserProfile.jsx
This was really bothering me lol
=> Add space between phone label and phone number in profiles

components/Post/Post.jsx, views/Comments/Comments.jsx, views/Feed/Feed.jsx
`isLiked` was never being sent when toggling a like so it was always undefined, resulting in likes not working.
Fixes https://github.com/CGUC/skybunk-mobile/issues/193
=> Add isLiked field to post data
